version: '3.2'
services:

  prometheus:
    build: './image'
    container_name: 'prometheus'
    restart: 'always'
    environment:
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'ENVIRONMENT=aws'
    network_mode: 'host'

